version: '3'

services:
  lldap:
    image: nitnelave/lldap:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      # For LDAP
      - "172.17.0.1:3890:3890"
      # For the web front-end
      - "172.17.0.1:17170:17170"
    volumes:
      - "./lldap_data:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      - UID=1000
      - GID=1000
      # - TZ=####/####
      - LLDAP_HTTP_URL=${LLDAP_HTTP_URL}
      - LLDAP_JWT_SECRET=REPLACE_WITH_RANDOM
      - LLDAP_LDAP_USER_PASS=${ADMIN_PASSWORD}
      - LLDAP_LDAP_USER_EMAIL=${ADMIN_EMAIL}
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
      - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=${LLDAP_SMTP_OPTIONS_ENABLE_PASSWORD_RESET}
      - LLDAP_SMTP_OPTIONS__SERVER=${LLDAP_SMTP_OPTIONS_SERVER}
      - LLDAP_SMTP_OPTIONS__PORT=${LLDAP_SMTP_OPTIONS_PORT}
      - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=${LLDAP_SMTP_OPTIONS_SMTP_ENCRYPTION}
      - LLDAP_SMTP_OPTIONS__USER=${LLDAP_SMTP_OPTIONS_USER}
      - LLDAP_SMTP_OPTIONS__PASSWORD=${LLDAP_SMTP_OPTIONS_PASSWORD}
