version: '3'

services:
  lldap:
    image: nitnelave/lldap:latest
    ports:
      # For LDAP
      - "172.17.0.1:3890:3890"
      # For the web front-end
      - "172.17.0.1:17170:17170"
    volumes:
      - "./lldap_data:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      - UID=10001
      - GID=10001
      - TZ=UTC
      - LLDAP_JWT_SECRET=${ADMIN_PASSWORD}
      - LLDAP_LDAP_USER_PASS=${ADMIN_PASSWORD}
      - LLDAP_LDAP_USER_EMAIL=admin@example.com
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com