version: '3'

services:
  lldap:
    image: nitnelave/lldap:stable
    ports:
      # For LDAP
      - "172.17.0.1:3890:3890"
      # For the web front-end
      - "172.17.0.1:17170:17170"
    volumes:
      - "./lldap_data:/data"
      # Alternatively, you can mount a local folder
      # - "./lldap_data:/data"
    environment:
      - UID=####
      - GID=####
      - TZ=####/####
      - LLDAP_JWT_SECRET=REPLACE_WITH_RANDOM
      - LLDAP_LDAP_USER_PASS=REPLACE_WITH_PASSWORD
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com